version: '3.8'
services:
  booking_saver:
    build: .
    container_name: booking_saver
    restart: unless-stopped
    volumes:
      - ./:/app
      - db_data:/app/data
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env
    environment:
      - INIT_SHEETS=1
      - GOOGLE_CREDENTIALS_JSON=/app/service_account.json

volumes:
  db_data:
