version: '3.8'
services:
  booking_saver:
    build: .
    container_name: booking_saver
    restart: unless-stopped
    volumes:
      - ./:/app
      - db_data:/app/data
    env_file:
      - .env
    environment:
      - INIT_SHEETS=1

volumes:
  db_data:
